config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # require 'sidekiq/web'
  devise_for :users
  # mount Sidekiq::Web => '/sidekiq'

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  root to: "pages#index"
  resources :users do
    root to: "users#show"
  end
  resources :buckets
  resources :financial_authentications

  authenticate :admin do
    # mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  type                   :string
#  public_token           :string
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_type                  (type)
#  index_users_on_unlock_token          (unlock_token) UNIQUE
#

class User < ApplicationRecord
  require 'api/plaid'

  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable

  has_many :buckets, -> { rank(:row_order) }, inverse_of: :user

  delegate :incomes, :fixed_costs, :financial_goals, to: :buckets

  # def send_devise_notification(notification, *args)
  #   devise_mailer.send(notification, self, *args).deliver_later
  # end

  def monthly_income_amount
    @monthly_income_amount ||= incomes.reorder(nil).pluck('sum(frequency * amount)')[0].to_f
  end

  def allotted_monthly_fixed_costs_amount
    monthly_income_amount * 0.5
  end

  def allotted_monthly_financial_goals_amount
    monthly_income_amount * 0.2
  end

  def allotted_monthly_flexible_spendings_amount
    monthly_income_amount * 0.3
  end

  def actual_incomes
    @actual_incomes ||= incomes.map{ |b| b.included_transactions }.flatten
  end

  def actual_incomes_amount
    actual_incomes.map{ |i| i.amount.abs }.sum
  end

  def actual_fixed_costs
    @actual_fixed_costs ||= fixed_costs.map{ |b| b.included_transactions }.flatten
  end

  def actual_fixed_costs_amount
     actual_fixed_costs.map(&:amount).sum
  end

  def actual_financial_goals
    @actual_financial_goals ||= financial_goals.map{ |b| b.included_transactions }.flatten
  end

  def actual_financial_goals_amount
    actual_financial_goals.map(&:amount).sum
  end

  def actual_flexible_spendings
    # this is array math, to remove objects from current_transactions
    @actual_flexible_spendings ||= current_transactions - actual_incomes - actual_fixed_costs - actual_financial_goals
  end

  def actual_flexible_spendings_amount
    actual_flexible_spendings.map(&:amount).sum
  end

  def current_transactions
    @current_transactions ||= plaid_user.current_transactions
  end

  def recent_transactions
    @recent_transactions ||= plaid_user.recent_transactions
  end

  def get_token
    @token ||= Plaid.exchange_token(public_token).access_token
  end

  def plaid_user(levels: %w(connect))
    @plaid_user ||= Api::Plaid.new(get_token, api_levels: levels)
    # call '#upgrade' on this object to promote api_level
  end

  # def set_bucket_defaults
  #   return unless public_token
  #   return if buckets.any?
  #   plaid_user.connect

  #   plaid_user.recurring_costs.each do |t|
  #     self.buckets << FixedCost.create(name: t.name, amount: t.amount, original_category: t.category)
  #   end
  #   plaid_user.recurring_payments.each do |t|
  #     self.buckets << FinancialGoal.create(name: t.name, amount: t.amount, original_category: t.category)
  #   end
  #   plaid_user.recurring_incomes.each do |t|
  #     self.buckets << Income.create(name: t.name, amount: t.amount.abs, original_category: t.category)
  #   end

  #   self
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.includes(:buckets).find_by_id(params[:id])
    @serialized_user = ActiveModel::SerializableResource.new(@user)

    # render json: @user
    # render json: @user.current_transactions
    # render json: @user.recent_transactions
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.slim
/ .container
/   .span4
/     h2 Incomes (#{number_to_currency(@user.actual_incomes_amount)} / #{number_to_currency(@user.monthly_income_amount)})
/     ul#incomes.bucket
/       = render collection: @user.incomes, partial: 'buckets/bucket'

/ .container
/   .span4
/     h2 style=("color:#{percent_color(FixedCost.percent_filled(@user))}") Fixed Costs 50% (#{number_to_currency(@user.actual_fixed_costs_amount)} / #{number_to_currency(@user.allotted_monthly_fixed_costs_amount)})
/     ul#fixed_costs.bucket
/       = render collection: @user.fixed_costs, partial: 'buckets/bucket'
/   .span4
/     h2 style=("color:#{percent_color(FinancialGoal.percent_filled(@user))}") Financial Goals 20% (#{number_to_currency(@user.actual_financial_goals_amount)} / #{number_to_currency(@user.allotted_monthly_financial_goals_amount)})
/     ul#financial_goals.bucket
/       = render collection: @user.financial_goals, partial: 'buckets/bucket'
/   .span4
/     h2 style=("color:#{percent_color(FlexibleSpending.percent_filled(@user))}") Flexible Spending 30% (#{number_to_currency(@user.actual_flexible_spendings_amount)} / #{number_to_currency(@user.allotted_monthly_flexible_spendings_amount)})
/     ul#flexible_spendings.transaction
/       = render collection: @user.actual_flexible_spendings, partial: 'transactions/transaction'
.full-vertical
  .container
    - if @user.public_token.present?
      = react_component 'User', @serialized_user
    - else
      / = link_to 'Link Bank', '#', id: 'plaid-link-button'
      = form_tag financial_authentications_path, method: :post, id: "plaid-auth"

      script(
        src="https://cdn.plaid.com/link/stable/link-initialize.js"
        data-client-name="50/20/30"
        data-form-id="plaid-auth"
        data-key="1dfbec6dadf32e8d394703a7cc284b"
        data-product="connect"
        data-env="tartan")